// Generated by gencpp from file detect/pose.msg
// DO NOT EDIT!


#ifndef DETECT_MESSAGE_POSE_H
#define DETECT_MESSAGE_POSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace detect
{
template <class ContainerAllocator>
struct pose_
{
  typedef pose_<ContainerAllocator> Type;

  pose_()
    : translate_x(0)
    , translate_y(0)
    , translate_z(0)  {
    }
  pose_(const ContainerAllocator& _alloc)
    : translate_x(0)
    , translate_y(0)
    , translate_z(0)  {
  (void)_alloc;
    }



   typedef int32_t _translate_x_type;
  _translate_x_type translate_x;

   typedef int32_t _translate_y_type;
  _translate_y_type translate_y;

   typedef int32_t _translate_z_type;
  _translate_z_type translate_z;




  typedef boost::shared_ptr< ::detect::pose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::detect::pose_<ContainerAllocator> const> ConstPtr;

}; // struct pose_

typedef ::detect::pose_<std::allocator<void> > pose;

typedef boost::shared_ptr< ::detect::pose > posePtr;
typedef boost::shared_ptr< ::detect::pose const> poseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::detect::pose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::detect::pose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace detect

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'detect': ['/home/luan/drill/src/detect/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::detect::pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detect::pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detect::pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detect::pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detect::pose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detect::pose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::detect::pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "59c5883f87076ea70156330eac5c4510";
  }

  static const char* value(const ::detect::pose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x59c5883f87076ea7ULL;
  static const uint64_t static_value2 = 0x0156330eac5c4510ULL;
};

template<class ContainerAllocator>
struct DataType< ::detect::pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "detect/pose";
  }

  static const char* value(const ::detect::pose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::detect::pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 translate_x\n\
int32 translate_y\n\
int32 translate_z\n\
";
  }

  static const char* value(const ::detect::pose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::detect::pose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.translate_x);
      stream.next(m.translate_y);
      stream.next(m.translate_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::detect::pose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::detect::pose_<ContainerAllocator>& v)
  {
    s << indent << "translate_x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.translate_x);
    s << indent << "translate_y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.translate_y);
    s << indent << "translate_z: ";
    Printer<int32_t>::stream(s, indent + "  ", v.translate_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DETECT_MESSAGE_POSE_H
